- name: Update apt cache
  apt:
    update_cache: 'yes'
  when: 'ansible_distribution in [''Debian'', ''Ubuntu'']'
- name: Install build tools on Debian/Ubuntu
  apt:
    name:
      - gcc
      - g++
      - make
      - cmake
      - build-essential
      - git
      - autoconf
      - curl
      - libtool
      - libssl-dev
      - libcurl4-openssl-dev
      - libz-dev
      - systemd-coredump
      - liblz4-tool
      - automake
    state: latest
  when: 'ansible_distribution in [''Debian'', ''Ubuntu'']'
- name: Install build tools on CentOS/RedHat
  yum:
    name:
      - gcc
      - gcc-c++
      - make
      - cmake
      - git
      - autoconf
      - curl
      - libtool
      - openssl-devel
      - libcurl-devel
      - zlib-devel
      - automake
    state: latest
  when: 'ansible_distribution in [''CentOS'', ''RedHat'']'
- name: Install libtool-bin (Debian/Ubuntu only)
  apt:
    name: libtool-bin
    state: latest
  when: 'ansible_distribution in [''Debian'', ''Ubuntu'']'
  ignore_errors: 'yes'
- name: Make source directory writable
  file:
    path: /usr/local/src
    state: directory
    mode: '0777'
- name: Checkout drachtio-server
  git:
    repo: 'https://github.com/davehorton/drachtio-server.git'
    dest: /usr/local/src/drachtio-server
    version: '{{ drachtioBranch }}'
    depth: 50
    accept_hostkey: 'yes'
    force: 'yes'
  become: 'no'
  register: checkout
- name: Build drachtio-server
  shell: >-
    ./autogen.sh && mkdir -p build && cd build && ../configure
    CPPFLAGS='-DNDEBUG' && make && make install
  args:
    executable: /bin/bash
    chdir: /usr/local/src/drachtio-server/
    creates: /usr/local/src/drachtio-server/build/drachtio
  become: 'yes'
  notify: restart drachtio
  when: checkout.changed
- name: Create drachtio log directories
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ drachtioLogFileDirectory }}'
    - '{{ drachtioLogArchiveDirectory }}'
  when: checkout.changed
- name: Create drachtio config file
  template:
    src: drachtio.conf.xml.j2
    dest: /etc/drachtio.conf.xml
    mode: '0644'
    owner: root
    group: root
  notify: restart drachtio
  when: checkout.changed
- name: Create systemd unit file
  template:
    src: drachtio-systemd-script.j2
    dest: /etc/systemd/system/drachtio.service
    mode: '0644'
    owner: root
    group: root
  notify: restart drachtio
  when: ansible_service_mgr == 'systemd' and checkout.changed
- name: Reload systemd
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd' and checkout.changed
- name: Remove source code
  file:
    path: /usr/local/src/drachtio-server
    state: absent
  when: remove_source | bool
